[package]
name = "rust_packetdump"
version = "0.1.0"
authors = ["Erick Poppe <epoppe@agetic.gob.bo>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pnet = "0.26.0"
structopt = "0.3.15"
etherparse = "0.9.0"
